Repository iamakashrout/Dev-Discussion-Platform, pull requests merged in 2025-04, with the labels that each got.

#11 Solved #9 : Integrated Ask-me-Anything Chatbot
  backend/controllers/gemini/context.js
  backend/controllers/gemini/geminiController.js
  backend/index.js
  backend/package.json
  backend/routes/chatbotRoutes.js
  frontend/src/Home.jsx
  frontend/src/components/Chatbot/HelpButton.css
  frontend/src/components/Chatbot/HelpButton.jsx
  frontend/src/components/Chatbot/HelpChat.css
  frontend/src/components/Chatbot/HelpChat.jsx
  frontend/src/config.js
Labels: pwoc, hard

#18 Solved #16 : Created a ReadMe file with all the latest features added
  README.md
Labels: pwoc, easy

#20 friends pages done and finalized
  backend/controllers/authControllers.js
  backend/controllers/userControllers.js
  backend/index.js
  backend/models/forgotpassword.js
  backend/models/userModel.js
  backend/package.json
  backend/routes/authRoutes.js
  backend/routes/userRoutes.js
  frontend/package.json
  frontend/src/App.js
  frontend/src/Login.jsx
  frontend/src/Network.jsx
  frontend/src/UserList.jsx
  frontend/src/components/ForgotPassword/ForgotPassword.css
  frontend/src/components/ForgotPassword/ForgotPassword.jsx
  frontend/src/components/ForgotPassword/ResetPassword.css
  frontend/src/components/ForgotPassword/ResetPassword.jsx
  frontend/src/components/ForgotPassword/VerifyOtp.css
  frontend/src/components/ForgotPassword/VerifyOtp.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/config.js
Labels: pwoc, medium

#21 Solved #19 : Designed Logo and added it to the website, Changed the display of site on the taskbar
  frontend/public/DevSphere1.png
  frontend/public/index.html
  frontend/src/DevSphere2.png
  frontend/src/Login.jsx
  frontend/src/Register.jsx
  frontend/src/components/NavBar.css
  frontend/src/components/NavBar.jsx
Labels: pwoc, easy

#22 Otp verification and password reset functionality
  backend/controllers/authControllers.js
  backend/routes/authRoutes.js
  frontend/src/App.js
  frontend/src/UserList.jsx
  frontend/src/components/ForgotPassword/ForgotPassword.jsx
  frontend/src/components/ForgotPassword/ResetPassword.jsx
  frontend/src/components/ForgotPassword/VerifyOtp.jsx
  frontend/src/components/Password/ForgotPassword.css
  frontend/src/components/Password/ForgotPassword.jsx
  frontend/src/components/Password/ResetPassword.css
  frontend/src/components/Password/ResetPassword.jsx
  frontend/src/components/Password/VerifyOtp.css
  frontend/src/components/Password/VerifyOtp.jsx
  frontend/src/config.js
Labels: pwoc, medium

#24 register verification done
  backend/controllers/authControllers.js
  backend/models/userModel.js
  backend/routes/authRoutes.js
  frontend/src/App.js
  frontend/src/Register.jsx
  frontend/src/components/Password/VerifyOtpRegister.css
  frontend/src/components/Password/VerifyOtpRegister.jsx
Labels: pwoc, medium

#28 Implemented text to speech feature in chatbot
  frontend/src/components/Chatbot/HelpChat.css
  frontend/src/components/Chatbot/HelpChat.jsx
Labels: pwoc, hard

#30 Implement text highlight feature during text to speech in chatbot issue #29
  frontend/src/components/Chatbot/HelpChat.css
  frontend/src/components/Chatbot/HelpChat.jsx
Labels: pwoc, medium

#36 added a search bar for users to search using name and location
  frontend/src/UserList.jsx
Labels: pwoc, medium

#38 Implement voice search in resources and categories page issue #37
  frontend/src/CategoryPage.css
  frontend/src/CategoryPage.jsx
  frontend/src/Resources.jsx
Labels: pwoc, medium

#40 Implement voice search in user search bar issue #39
  frontend/src/UserList.jsx
Labels: pwoc, medium

#43 done profile page
  backend/controllers/userControllers.js
  backend/routes/userRoutes.js
  frontend/package.json
  frontend/src/App.js
  frontend/src/EditProfile.css
  frontend/src/EditProfile.jsx
  frontend/src/Profile.jsx
  frontend/src/ProfilePage.css
  frontend/src/components/NavBar.jsx
  frontend/src/config.js
Labels: pwoc, medium

#44 added a posts feature to create and view posts
  backend/controllers/postController.js
  backend/index.js
  backend/models/postModel.js
  backend/routes/postRoutes.js
  frontend/src/App.js
  frontend/src/components/NavBar.jsx
  frontend/src/components/Posts/Posts.css
  frontend/src/components/Posts/Posts.jsx
  frontend/src/components/Posts/createPost.css
  frontend/src/components/Posts/createPost.jsx
  frontend/src/components/Posts/createPostButton.css
  frontend/src/components/Posts/createPostButton.jsx
Labels: pwoc, hard
